/*
 * This source file was generated by the Gradle 'init' task
 */
package VirtualScrollAccessSystem;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.stage.Stage;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.Image;

public class App extends Application{

    public static String name;
    public static String type;
    public static Boolean flag;
    public static String page;

    @Override
    public void start(Stage stage) throws Exception {
        
        Parent root = FXMLLoader.load(getClass().getResource("/Login.fxml"));

        Image image = new Image("hatImage.png");
        stage.getIcons().add(image);

        stage.setTitle("VSAS Login");

        stage.setScene(new Scene(root));
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}